apiVersion: v1
kind: Service
metadata:
  name: bank-payment-service
spec:
  type: NodePort
  selector:
    app: bank-payment-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080