apiVersion: v1
kind: Service
metadata:
  name: config-management-service
spec:
  type: NodePort
  selector:
    app: config-management-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080