apiVersion: v1
kind: Service
metadata:
  name: config-management-service-db
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: config-management-service-db-port
  selector:
    app: config-management-service-db
    tier: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-management-service-db
spec:
  selector:
    matchLabels:
      app: config-management-service-db
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: config-management-service-db
        tier: db
    spec:
      containers:
        - image: mysql:5.6
          name: config-management-service-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-management-service-secrets
                  key: mysql-root-password
          ports:
            - containerPort: 3306
              name: config-management-service-db-port
          volumeMounts:
            - name: config-management-service-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: config-management-service-db-persistent-storage
          persistentVolumeClaim:
            claimName: config-management-service-pv-claim